### ISSUE TITLE
bug: Wrong use of postMessage.test

### ISSUE THREAD

**Issue by devdevx** [apiaddicts/openapi2postman#26]
# Bug Report

**Version:**

Latest

**Current behavior:**

The generated JS tests use `postMessage` that didn't exists.

```
try {
    json = pm.response.json();
    // pm.environment.set('var', json.data.variable);
} catch (e) {
    postMessage.test("JSON expected", function() {
        pm.expect(json, "responseBody not JSON").not.to.be.null;
    });
}
```

**Expected behavior:**

The generated JS tests use `pm` instead of `postMessage`.

```
try {
    json = pm.response.json();
    // pm.environment.set('var', json.data.variable);
} catch (e) {
    pm.test("JSON expected", function() {
        pm.expect(json, "responseBody not JSON").not.to.be.null;
    });
}
```

**Steps to reproduce:**

Generate a test

**Comment by AllT2709** [comment]
This issue is solved in 751a684
![postMessage](https://github.com/user-attachments/assets/381c67eb-3c6b-4d04-8fd9-0dab1601a35a)
