### ISSUE TITLE
bug: Schema validation tests are always commented

### ISSUE THREAD

**Issue by devdevx** [apiaddicts/openapi2postman#28]
# Bug Report

Using the latest version on npm, i am not able to generate collections where the schema tests are enabled, they are always commented.

**Comment by AllT2709** [comment]
To uncomment the schema tests, the validate_schema must be placed in the configuration environments setting true or false:

![validate_schema](https://github.com/user-attachments/assets/02f71e93-883a-41b6-984d-1d0d9df3781f)
