### ISSUE TITLE
feat: Configuration structure documentation

### ISSUE THREAD

**Issue by devdevx** [apiaddicts/openapi2postman#29]
# Feature Request

Currently the default configuration json is documented in the readme but is not a valid json, it also don't have all the available fields and you need to search for the in different pdf documents.

I suggest to improve the readme with the default config json in a valid format and an extended config json with all the fields available.

**Comment by AllT2709** [comment]
This issue is solve with the pr : a65451c

![actualización readme](https://github.com/user-attachments/assets/f40151a9-9059-44a2-a3a9-82be39054fb1)
