### ISSUE TITLE
feat: Imporve tv4 validation

### ISSUE THREAD

**Issue by devdevx** [apiaddicts/openapi2postman#30]
# Feature Request

The current tv4 validation only asserts a true/false result, and you need to open the console to check what was wrong.

The test result can be improved using the errors list as text message.

```
let checkRecursive = false;
let banUnknownProperties = true;
let schemaValidation = tv4.validateMultiple(pm.response.json(), JSON_SCHEMA, checkRecursive, banUnknownProperties);
pm.expect(schemaValidation.valid, schemaValidation.errors).to.be.true;
```

**Comment by AllT2709** [comment]
Change the tv4 validation for schema in pr: b7571c2
![tv4_validation](https://github.com/user-attachments/assets/6efaae0e-528b-406d-9ca5-167dff7362d4)
