### ISSUE TITLE
feat: Config flag for oneOf/anyOf

### ISSUE THREAD

**Issue by devdevx** [apiaddicts/openapi2postman#31]
# Feature Request

Currently the oneOf/anyOf cases only generate 1 call case with the first available case.

maybe we can have a new config flag to:
- Generate one call case for each definition in the oneOf body
- Generate one call case for each definition in the anyOf body and another one merging all of them

**Comment by AllT2709** [comment]
This issue is solve with the PR: 84a412b

There are a new flag to generate one call case with each definition in the oneOf and anyOf body
"generate_oneOf_anyOf":true or false

![picture074-1](https://github.com/user-attachments/assets/4c879b94-f915-4f96-82cd-5939d418b99e)
