### ISSUE TITLE
feat: add host from openapi. Select the rigth host using parameters and patterns. For example, if the host is "pre-apiquality" you should search the servers have "pattern"

### ISSUE THREAD

**Issue by admin-cloudappi** [apiaddicts/openapi2postman#36]
# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by AllT2709** [comment]
This feature is available in: 1785b7d

More info in #38
