### ISSUE TITLE
feat: comment examples section

### ISSUE THREAD

**Issue by admin-cloudappi** [apiaddicts/openapi2postman#37]
# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by AllT2709** [comment]
More information is needed to solve the issue
