### ISSUE TITLE
feat: add a new feature to get host and basepath using openapi

### ISSUE THREAD

**Issue by admin-cloudappi** [apiaddicts/openapi2postman#38]
# Feature Request

**add a new attribute to select the host and basepath for openapi. For example:
 "environments": [
        {
            "name" : "DEV",
            "postman_collection_name": "api-greetings_TestSuite_DEV",
            "postman_environment_name": "api-greetings_TestSuiteEnv_DEV",
           
            "port": 443,
            "target_folder": "./auto-generated/api-greetings_Postman_Collection",
            "custom_authorizations_file": "./auto-generated/api-greetings_Postman_Collection/authorizations.postman_collection.json",
            "microcks_headers": true,
            "host_pattern":"dev"
        }
    ]

in openapi you have to get path and basepath using this pattern

servers:
  - url: https://microcks.apiquality.io/rest/api-greetings-marco_986c6d43_V/v1
  - url: https://dev-api.cloudappi.net/api-template/v1
    description: Development server
  - url: https://api.cloudappi.net/api-template/v1
    description: Production server
**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by marcosanz-apiquality** [comment]
I think it's better change "host_pattern" for host_server_pattern:"%dev%"

**Comment by AllT2709** [comment]
This feature is avalable in: 1785b7d

![server_openapi](https://github.com/user-attachments/assets/248c5007-22ac-448a-8d4e-e14ebdd52748)
![server_openapi_environments](https://github.com/user-attachments/assets/a807cd69-347a-4bd0-b9b9-24bd712ff1d3)
