### ISSUE TITLE
bug: port need to add ":" before

### ISSUE THREAD

**Issue by admin-cloudappi** [apiaddicts/openapi2postman#39]
**DO NOT SUBMIT SECURITY REPORTS HERE**

If you have a security vulnerability, _please report it following our security policy_.

# Bug Report

** Error in port**

Actually the environments need to add ':' . The path need to put automatically the ":"  

**Actually the environments need to add ':' . The path need to put automatically the ":"   **

Always

**Expected behavior:**

You never should set the ":" in the port into the environment 

**Steps to reproduce:**

Generate the collection typing the port

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Comment by AllT2709** [comment]
This bug is fixed with the commit 4c962f3
