### ISSUE TITLE
bug: read_only is working bad

### ISSUE THREAD

**Issue by admin-cloudappi** [apiaddicts/openapi2postman#40]
**DO NOT SUBMIT SECURITY REPORTS HERE**

# Bug Report

**Amazing GitHub Template version:**

last version

**Current behavior:**

if you put read_only = false the openapi2postman is generating only readonly 

**Expected behavior:**

if you add read_only = false the tool sould generate all requests (post, put, ...)

**Steps to reproduce:**

put in file config into environtment read_only = false

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Comment by AllT2709** [comment]
Attached is a screenshot of a collection and its copy of the correct read_only functionality. When set to false, it generates all post, put and delete requests and if set to true, it generates only read requests. This is in the openapi2postman  last vesión 

![read_only_issue](https://github.com/user-attachments/assets/b745c5b3-585b-4711-be44-9fd4128df920)
