### ISSUE TITLE
feat: configure minimal tests for request

### ISSUE THREAD

**Issue by marcosanz-apiquality** [apiaddicts/openapi2postman#43]
# Feature Request

**Describe the Feature Request**

Generate one only request for each http code. 

**Describe Preferred Solution**

Generate only one test for each http response. 
You can add attribute "minimal_tests" to create the minimal collection 

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by AllT2709** [comment]
This issue is solved wiht the pr: 84a412b

the new flag is calling "minimal_endpoints" 
![minimal_request-2](https://github.com/user-attachments/assets/cbb09894-7c95-4e39-8b2e-0104f23c21ef)
![minimal_request](https://github.com/user-attachments/assets/8e914dab-e28b-4ffd-baa1-16587aa41835)

**Comment by AllT2709** [comment]
The implementation only takes the first parameter required to make the request
