### ISSUE TITLE
feat: Configure oauth with postman variables

### ISSUE THREAD

**Issue by marcosanz-apiquality** [apiaddicts/openapi2postman#48]
# Feature Request

**Describe the Feature Request**

Actually, your are creating oauth2 with external files. 

**Describe Preferred Solution**

You should create the autho get token directly into the postman collection and re-use the openapi information.

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by AllT2709** [comment]
This issue is solve with the pr: ed5bfa4

![oauth_token](https://github.com/user-attachments/assets/829344d6-96f1-4818-b6c6-3f9f1704140b)
![oauth_token-1](https://github.com/user-attachments/assets/ff8ab84e-8bd1-4230-b1fb-2c6d397a36fa)
